[tools]
node = "latest"
pnpm = "latest"
bun = "latest"
python = "latest"
rust = "latest"
go = "latest"
zig = "0.15.1"
ripgrep = "latest"
tmux = "latest"
lazygit = "latest"
neovim = "latest"
gum = "latest"
fzf = "latest"
github-cli = "latest"
yt-dlp = { version = "latest", rename_exe = "yt-dlp" }
lazydocker = "latest"
fd = "latest"
act = "latest"
pipx = "latest"
azure-cli = { version = "latest", uvx_args = "--prerelease=allow" }

[shell_alias]
update = "bash $HOME/dotfiles/update.sh"
quartz = "cd $HOME/dev/quartz/content/"
plugins = "cd $HOME/.config/nvim/lua/custom/plugins/"

[settings]
experimental = true
