[tools]
node = "24"
pnpm = "10"
bun = "1"
python = "3.14"
pipx = "1.11"
rust = "nightly"
go = "1.25"
lua = "5.1"
deno = "2.7"
ripgrep = "15"
tmux = "3"
neovim = "0.12"
tree-sitter = "latest"
lazygit = "latest"
gum = "latest"
fzf = "latest"
github-cli = "latest"
yt-dlp = { version = "latest", rename_exe = "yt-dlp" }
lazydocker = "latest"
fd = "latest"
azure-cli = { version = "latest", uvx_args = "--prerelease=allow" }
oh-my-posh = "latest"
kubectl = "latest"
azure-kubelogin = "latest"
kubectx = "latest"
kubens = "latest"
k9s = "latest"

[shell_alias]
update = "bash $HOME/dotfiles/update.sh"
dev = "cd $HOME/dev"
notes = "cd $HOME/dev/notes"
plugins = "cd $HOME/.config/nvim/lua/custom/plugins/"
gp = "gpauth batavia.banpuindo.co.id --browser 2>/dev/null | sudo gpclient connect batavia.banpuindo.co.id --client-version 6.1.4-711 --hip --cookie-on-stdin"
warpon = "warp-cli connect"
warpoff = "warp-cli disconnect"

[settings]
experimental = true
