[theme]
background = "#1e1e2e"
primary = "#cdd6f4"
secondary = "#94e2d5"
title = "#89dceb"
playing = "#a6e3a1"
playing_bg = "#1e1e2e"
highlight = "#cdd6f4"
highlight_bg = "#537d8c"
playing_selected = "#a6e3a1"
error = "#1e1e2e"
error_bg = "#f38ba8"
statusbar = "#89dceb"
statusbar_bg = "#313244"
statusbar_progress = "#89dceb"
cmdline = "#89dceb"
cmdline_bg = "#181825"
